### ISSUE TITLE
About toy experiment

### ISSUE THREAD

**Issue by planemanner** [polo5/ZeroShotKnowledgeTransfer#1]
Above all, thanks for your nice work.

I want to reproduce your toy experiment as a reference for my research.

Could you let me know what dataset is used for that experiment?

**Comment by polo5** [comment]
Hi, thank you for the feedback.

I've just added a notebook for the toy experiment which shows how the butterfly-looking toy dataset is produced. Note that for the toy experiment there is no generator, and instead the pseudo points are learned directly for simplicity. Please let me know if something is missing.

**Comment by planemanner** [comment]
@polo5 I have one more question. **Why you construct the generator like that ? Is there a special intuition or an idea for the generator?** When I tried changing the architecture of generator, if i replace your generator with others (ex) ResNet generator), the transfer performance had become lower than original one. As you mentioned it in your paper, i observed it. But Unlike this situation, if i use a generator having much lower performance in generating something, surprisingly, same situation was observed. So, i concluded that there exists some idea to construct generator guiding right way.

**Comment by polo5** [comment]
Hi, ideally the generator has a representational capacity that is comparable to the student. This is similar to GANs where we want the discriminator and generator to be "equally good" and learn at the same rate. I used a generic architecture inspired by this code base: https://github.com/eriklindernoren/PyTorch-GAN/blob/master/implementations/infogan/infogan.py

Feel free to let us know how your experiments go, as I haven't done an exhaustive search of the generator (maybe some layers like relational layers would help?). But please do open a seperate issue for results or further questions so people can access your comments :)
