### ISSUE TITLE
about gif image

### ISSUE THREAD

**Issue by WANGQI2788** [polo5/ZeroShotKnowledgeTransfer#2]
hi, the gif image is so cool. so i want to ask the software you used for that gif. many thanks.

**Comment by polo5** [comment]
Hi, I'm glad you like the gif. If you haven't managed to make one you can create snapshot pictures using notebooks/toy_experiment.ipynb and then convert them to a gif using the following:

```python
def images_to_gif(folder_path, output_name='movie.gif', duration=0.3):
    images = []
    for filename in sorted(os.listdir(folder_path)):
        path = os.path.join(folder_path, filename)
        images.append(imageio.imread(path))
    
    imageio.mimsave(output_name, images, duration=duration)
```

**Comment by WANGQI2788** [comment]
> Hi, I'm glad you like the gif. If you haven't managed to make one you can create snapshot pictures using notebooks/toy_experiment.ipynb and then convert them to a gif using the following:
> 
> ```python
> def images_to_gif(folder_path, output_name='movie.gif', duration=0.3):
>     images = []
>     for filename in sorted(os.listdir(folder_path)):
>         path = os.path.join(folder_path, filename)
>         images.append(imageio.imread(path))
>     
>     imageio.mimsave(output_name, images, duration=duration)
> ```

**Comment by WANGQI2788** [comment]
great, many thanks. it will help me a lot.
